name: Rust

on: [push]

jobs:
  build:

    name: ${{ matrix.os }} stable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build stable
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Build nightly
      run: cargo build --verbose
    

  # test:

  #   name: Build and test on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macOS-latest]

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose
